### ISSUE TITLE
Fetching data demo not working

### ISSUE THREAD

**Issue by stursby** [egoist/saber.js#2]
Hey @egoist 👋. I see you've made another lib ha!! I was trying out the [fetching data](https://github.com/egoist/saber.js#fetching-data) snippet and getting the following error:

![image](https://user-images.githubusercontent.com/527849/40448828-4342da6a-5e9c-11e8-97d0-bf3206e7c4a6.png)

My code is the same as in your example

```vue
<template>
  <div>{{ post.title }}</div>
</template>

<saber>
import axios from 'axios'

export default {
  async data() {
    const { data: post } = await axios
      .get('https://jsonplaceholder.typicode.com/posts/1')

    return {
      post
    }
  }
}
</saber>

```

Any thoughts?

**Comment by egoist** [comment]
Fixed in v0.1.3
