### ISSUE TITLE
Customizable HTML template

### ISSUE THREAD

**Issue by fb-erik** [egoist/saber.js#8]
Is it possible to change the HTML-template, or use something like a layout-file as in Nuxt?

**Comment by egoist** [comment]
> Is it possible to change the HTML-template

Why do you need this? https://github.com/egoist/saber.js#manipulating-head is this what you want?

> use something like a layout-file as in Nuxt?

There're many ways to build a layout system.

```js
// saber.app.js
import AppLayout from './AppLayout.vue'
import DashboardLayout from './DashboardLayout.vue'

Vue.component('AppLayout', AppLayout)
Vue.component('DashboardLayout', DashboardLayout)
```

Then in your route component:

```vue
<template>
  <app-layout>
    <h1>app</h1>
  </app-layout>
</template>
```

**Comment by fb-erik** [comment]
Thanks for the explanation, I was thinking about how to set html and body attributes to name a few things, but I realise now that I "head" is actually the same as "metaInfo"? Like this?

```js
export default {
  head: {
    title: 'My Website',
    bodyAttrs: {
      bar: 'baz'
    },
    htmlAttrs: {
      foo: 'bar',
      amp: undefined
    }
  }
}
```
but there is no way of customizing the `<div id="__saber"></div>` wrapper is there?

**Comment by egoist** [comment]
Yeah `#__saber` is the element we mount the app to, you should avoid touching that. If you want to style the element, I think it's fine to use the id.
