### ISSUE TITLE
Nested routes issue?

### ISSUE THREAD

**Issue by fb-erik** [egoist/saber.js#9]
if I create pages like the nested pages example:

```bash
└── pages
    ├── index.vue
    ├── users
    │   ├── [name].vue
    │   └── index.vue # required
    └── users.vue     # required
```

then nothing under `/users` will load, instead I only see the `users.vue` page content.

if I remove the `users/index.vue` file, nested pages load properly.

**Comment by egoist** [comment]
that's working fine for me, can you post what is generated in `.saber/templates/routes.js`? 

maybe you forget to add `<router-view>` in the `users.vue` component?

**Comment by fb-erik** [comment]
Sorry, I did forget the `<router-view>`. Thanks!
